apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-browser-deployment
  namespace: staging-namespace
spec:
  selector:
    matchLabels:
      app: s3-browser
      env: staging
  template:
    metadata:
      labels:
        app: s3-browser
        env: staging
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lab-server
      containers:
      - name: s3-browser
        image: IMAGE_NAME
        resources:
          # requests:
          #   memory: "64Mi"
          #   cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000