apiVersion: v1
kind: Service
metadata:
  name: s3-browser-service
  namespace: staging-namespace
spec:
  selector:
    app: s3-browser
    env: staging
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort